// This struct definition should be in your "MusicData.h" file.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "MusicData.generated.h"

UENUM(BlueprintType)
enum class EGameplayEntryType : uint8
{
	HitObject   UMETA(DisplayName = "Hit Object"),
	TimingPoint UMETA(DisplayName = "Timing Point"),
	Break       UMETA(DisplayName = "Break"),
	AudioBeat   UMETA(DisplayName = "Audio Beat") // This is not generated by the script, but kept for your use
};


USTRUCT(BlueprintType)
struct FMusicData : public FTableRowBase
{
	GENERATED_BODY()

public:
	// --- Common Data (All Types) ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data")
	int32 TimestampMS = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data")
	EGameplayEntryType EntryType = EGameplayEntryType::HitObject;

	// --- Global Map Difficulty (Applies to all entries) ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Difficulty")
	float HPDrainRate = 5.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Difficulty")
	float CircleSize = 5.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Difficulty")
	float OverallDifficulty = 5.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Difficulty")
	float ApproachRate = 5.0f;

	// --- Hit Object Data ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Hit Object", meta=(EditCondition="EntryType == EGameplayEntryType::HitObject"))
	int32 HitObjectType = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Hit Object", meta=(EditCondition="EntryType == EGameplayEntryType::HitObject"))
	int32 HitSound = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Hit Object", meta=(EditCondition="EntryType == EGameplayEntryType::HitObject"))
	int32 SliderEndTimeMS = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Hit Object", meta=(EditCondition="EntryType == EGameplayEntryType::HitObject"))
	int32 Repeats = 0;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Hit Object", meta=(EditCondition="EntryType == EGameplayEntryType::HitObject"))
	float SliderTickRate = 1.f;
	
	// --- Break Period Data ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Break", meta=(EditCondition="EntryType == EGameplayEntryType::Break"))
	int32 BreakEndTimeMS = 0;

	// --- Timing Point Data ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Timing Point", meta=(EditCondition="EntryType == EGameplayEntryType::TimingPoint"))
	int32 Uninherited = 0; // 1 for uninherited (red), 0 for inherited (green)

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Timing Point", meta=(EditCondition="EntryType == EGameplayEntryType::TimingPoint"))
	float BeatLength = 500.f; // For uninherited, this is ms per beat. For inherited, it's a -100/velocity multiplier.

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Timing Point", meta=(EditCondition="EntryType == EGameplayEntryType::TimingPoint"))
	int32 Meter = 4; // e.g., 4 for 4/4 time signature

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Timing Point", meta=(EditCondition="EntryType == EGameplayEntryType::TimingPoint"))
	int32 Effects = 0; // Bitmask for kiai time, etc.
	
	// --- Audio Beat Data (if you do separate audio analysis) ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Music Data|Audio", meta=(EditCondition="EntryType == EGameplayEntryType::AudioBeat"))
	float AudioBeatStrength = 0.f;
};