#include "RhythmDataGenerator.h"
#include "SongConfigurationData.h"
#include "Engine/DataTable.h"
#include "Factories/DataTableFactory.h"
#include "Modules/ModuleManager.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetToolsModule.h"
#include "Framework/Notifications/NotificationManager.h"
#include "Widgets/Notifications/SNotificationList.h"
#include "Misc/PackageName.h"
#include "Editor.h"

#define LOCTEXT_NAMESPACE "RhythmDataGenerator"

void URhythmDataGenerator::GenerateRhythmDataTable(USongConfigurationData* SongConfig, const TArray<FGameplayRhythmSection>& SectionsToExport)
{
	// --- 1. VALIDATION ---
	if (!SongConfig)
	{
		UE_LOG(LogTemp, Error, TEXT("RhythmDataGenerator: Cannot generate DataTable without a source SongConfigurationData asset."));
		return;
	}
	if (SectionsToExport.Num() == 0)
	{
		UE_LOG(LogTemp, Warning, TEXT("RhythmDataGenerator: No sections were generated by the analysis. No DataTable will be created."));
		return;
	}

	// --- 2. PREPARE SAVE PATH (Quality of Life Feature A) ---
	// Get the path of the source asset to suggest a smart default location.
	const FString SourceAssetPath = SongConfig->GetPathName();
	FString DefaultSavePath = FPackageName::GetLongPackagePath(SourceAssetPath) + TEXT("/");
	FString DefaultSaveName = FString::Printf(TEXT("DT_%s_RhythmData"), *SongConfig->GetName());

	FString PackageName;
	FString AssetName;

	// Use the AssetTools module to prompt the user for a save location.
	// This is the modern and correct way to do it.
	FAssetToolsModule& AssetToolsModule = FModuleManager::Get().LoadModuleChecked<FAssetToolsModule>("AssetTools");
	AssetToolsModule.Get().CreateUniqueAssetName(DefaultSavePath + DefaultSaveName, TEXT(""), PackageName, AssetName);
	
	FString UserSelectedPath;
	// This function is unfortunately not exposed to be called directly.
	// Instead, we create the asset and then let the user rename it if they wish.
	// The primary method is to use CreateAssetWithDialog, which is what we will do.

	// --- 3. CREATE THE DATATABLE ASSET WITH A DIALOG ---
	UDataTableFactory* DataTableFactory = NewObject<UDataTableFactory>();
	DataTableFactory->Struct = FGameplayRhythmSection::StaticStruct();

	// This will open the "Save Asset" dialog, pre-filled with our smart path.
	// The user can accept it, or choose a new location and name.
	UObject* NewAsset = AssetToolsModule.Get().CreateAssetWithDialog(
		UDataTable::StaticClass(),
		DataTableFactory,
		FName(*DefaultSavePath) // The dialog needs a folder path, not a full asset path
	);

	UDataTable* NewDataTable = Cast<UDataTable>(NewAsset);

	if (!NewDataTable)
	{
		// User cancelled the dialog or something went wrong. This is not an error.
		UE_LOG(LogTemp, Log, TEXT("RhythmDataGenerator: DataTable creation was cancelled by the user."));
		return;
	}

	// --- 4. POPULATE THE DATATABLE ---
	for (int32 i = 0; i < SectionsToExport.Num(); ++i)
	{
		const FGameplayRhythmSection& Section = SectionsToExport[i];
		const FName RowName = FName(*FString::Printf(TEXT("Section_%03d"), i)); // Use %03d for nice padding (001, 002...)
		NewDataTable->AddRow(RowName, Section);
	}

	// The asset is already saved by CreateAssetWithDialog, but we mark it dirty
	// because we have added rows to it.
	NewDataTable->MarkPackageDirty();
	FAssetRegistryModule::AssetCreated(NewDataTable); // Notify the asset registry

	// --- 5. FINALIZE AND NOTIFY (Quality of Life Feature B) ---
	// Ping the notification manager to let the user know it worked.
	FNotificationInfo Info(FText::Format(LOCTEXT("RhythmDataTableGenerated", "Successfully generated {0}"), FText::FromString(NewDataTable->GetName())));
	Info.ExpireDuration = 5.0f;
	FSlateNotificationManager::Get().AddNotification(Info);

	// Automatically select and highlight the new asset in the Content Browser.
	if (GEditor)
	{
		GEditor->SyncBrowserToObjects(TArray<UObject*>{ NewDataTable });
	}
}

#undef LOCTEXT_NAMESPACE