// --- START OF FILE SongConfigurationData.h ---

// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "MusicData.h"
#include "SongConfigurationData.generated.h"

class UDataTable;

// The FSectionOverride struct is no longer needed and has been REMOVED.

UCLASS(BlueprintType)
class PROJECT_CIRCLE_API USongConfigurationData : public UDataAsset
{
	GENERATED_BODY()

public:
	// --- CORE GAMEPLAY DATA ---
	/** The specific DataTable whose notes will be used for gameplay events. This is the map the player "plays". */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gameplay")
	TObjectPtr<UDataTable> GameplayMap;

	// --- RHYTHM ANALYSIS DATA ---
	/** All other DataTables to be used for rhythm analysis. The GameplayMap should NOT be included in this list. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Analysis")
	TArray<TObjectPtr<UDataTable>> AdditionalAnalysisMaps;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Analysis", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float DifficultyBias = 0.0f;
	
	/**
	 * OPTIONAL: A specific map from the 'AdditionalAnalysisMaps' list to use as the base for structural analysis.
	 * If left empty, the system will automatically choose the one with the highest OverallDifficulty from the analysis list.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Analysis", meta=(DisplayName="Structural Base Map (Optional Override)"))
	TObjectPtr<UDataTable> StructuralAnalysisBaseMapOverride;

	// --- GENERATED GAMEPLAY ASSETS ---
	/** The final, processed rhythm data used for gameplay. This is generated by the 'GenerateRhythmAssets' function. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets")
	TObjectPtr<UDataTable> GeneratedRhythmProfile;

	/** A copy of the GameplayMap, used for runtime note events. This is generated by the 'GenerateRhythmAssets' function. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets")
	TObjectPtr<UDataTable> GeneratedNoteData;

#if WITH_EDITOR
	/**
	 * Runs the full song analysis and generates the Rhythm Profile and Note Data DataTables.
	 * The generated assets will be automatically assigned to the 'Generated Assets' properties above.
	 */
	UFUNCTION(CallInEditor, Category = "Rhythm Generation")
	void GenerateRhythmAssets();
#endif
};