#pragma once

#include "CoreMinimal.h"
#include "MusicAnalysisTypes.h"
#include "MusicData.h"
#include "URhythmAnalysisProfile.generated.h"

/**
 * A data object that holds the complete, processed rhythmic profile of a song.
 * It is generated by the static RunSongAnalysis function and contains all the
 * necessary data for the MusicAnalysisSubsystem to drive gameplay.
 */
UCLASS(BlueprintType)
class PROJECT_CIRCLE_API UURhythmAnalysisProfile : public UObject
{
	GENERATED_BODY()

public:
	/**
	 * Creates a new UAnalyzedSongData object by performing a full analysis based on the given parameters.
	 * This is the primary entry point for all analysis, for both runtime and editor tools.
	 */
	UFUNCTION(BlueprintCallable, Category = "Music Analysis")
	static UURhythmAnalysisProfile* RunSongAnalysis(UObject* Outer, USongConfigurationData* SongConfig);

	// --- Public Data Accessors ---
	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	const TArray<FRhythmSectionProfile>& GetRhythmSections() const { return Result.RhythmSections; }

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	const TArray<FMusicData>& GetRuntimeEventTimeline() const { return RuntimeEventTimeline; }

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	const TMap<int32, FMusicData>& GetMasterUninheritedTimingPoints() const { return MasterUninheritedTimingPoints; }

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	int32 GetAbsoluteSongEndTimeMS() const { return AbsoluteSongEndTimeMS; }

private:
	// --- Private Implementation ---

	// The main analysis logic, which now takes the single parameter object.
	void AnalyzeRhythmSections(const FSongAnalysisParameters& Parameters);
	
	bool GatherCouncilData(const TArray<UDataTable*>& WeightedAnalysisMaps, float DifficultyBias, TArray<FConfidentHitObject>& OutConfidentHitObjects);

	void ApplyOverrides(USongConfigurationData* SongConfig);

	// --- Stored Analysis Results ---
	// This struct is defined in MusicAnalysisTypes.h now
	UPROPERTY()
	FSongAnalysisResult Result;

	UPROPERTY()
	TArray<FMusicData> RuntimeEventTimeline;

	UPROPERTY()
	TMap<int32, FMusicData> MasterUninheritedTimingPoints;

	UPROPERTY()
	int32 AbsoluteSongEndTimeMS = -1;

	// Friend class declaration allows the subsystem to call the private ApplyOverrides function.
	friend class UMusicAnalysisSubsystem;
};