#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "PcMusicConfigurationData.generated.h"

class UMusicGameplayEventDefinition;
class UMetaSoundSource;
class UDataTable;
struct FPcMusicGameplayEvents;

UCLASS(BlueprintType)
class PROJECT_CIRCLE_API UPcMusicConfigurationData : public UDataAsset
{
	GENERATED_BODY()

public:

	// --- General Music Data ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "General Music Data")
	FName SongName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "General Music Data")
	TObjectPtr<UMetaSoundSource> MainMusicMetaSound;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "General Music Data")
	TObjectPtr<USoundWave> SongWaveAsset;

	// --- Core Source Data ---
	/** The source DataTable containing the raw, imported music data (FPcImportedMusicData). This is the master source for notes. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Core Source Data")
	TObjectPtr<UDataTable> ImportedMusicDataProfile;

	/** Used to initialize a default behaviour for each note played in the game. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Core Source Data")
	TObjectPtr<UMusicGameplayEventDefinition> DefaultMusicNoteBehaviour;

	/** Used to initialize a default behaviour for each event marked within the game. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Core Source Data")
	TObjectPtr<UMusicGameplayEventDefinition> DefaultMusicEventBehaviour;

	// --- Generated Gameplay Assets ---
	/** The final, processed rhythm events data used for gameplay. This is generated by the 'Generate' button. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets")
	TObjectPtr<UDataTable> GeneratedMusicEventsProfile;

	/** The final, processed note data used for runtime events. This is generated by the 'Generate' button. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets")
	TObjectPtr<UDataTable> GeneratedMusicNotesProfile;

#if WITH_EDITOR
	/**
	 * Runs the full song analysis and generates/updates the two DataTable assets above.
	 * You must save THIS configuration asset after running the generation.
	 */
	UFUNCTION(CallInEditor, Category = "Generated Assets")
	void GenerateRhythmAssets();
#endif

	// --- Advanced Analysis Data ---
	/** Additional DataTables to be used for rhythm analysis. The GameplayMap should NOT be included in this list. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Advanced Analysis Data", meta = (AdvancedDisplay))
	TArray<TObjectPtr<UDataTable>> AdditionalAnalysisMaps;

	/** A bias from -1 (easier) to 1 (harder) to weigh the analysis maps. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Advanced Analysis Data", meta = (AdvancedDisplay, ClampMin = "-1.0", ClampMax = "1.0"))
	float DifficultyBias = 0.0f;
	
private:
#if WITH_EDITOR
	// --- Private Helper Functions for Generation ---
	UDataTable* GenerateRhythmProfileTable(const TArray<FPcMusicGameplayEvents>& SectionsToExport);
	UDataTable* GenerateNotesTable();
#endif
};