// --- START OF FILE URhythmAnalysisProfile.h ---

#pragma once

#include "CoreMinimal.h"
#include "PcMusicAnalysisTypes.h"
#include "PcMusicAnalyzer.generated.h"

/**
 * A data object that holds the complete, processed rhythmic profile of a song.
 * It is generated by the static RunSongAnalysis function and contains all the
 * necessary data for the MusicAnalysisSubsystem to drive gameplay.
 */
UCLASS(BlueprintType)
class PROJECT_CIRCLE_API UPcMusicAnalyzer : public UObject
{
	GENERATED_BODY()

public:
	/**
	 * Creates a new UAnalyzedSongData object by performing a full analysis based on the given parameters.
	 * This is the primary entry point for all analysis, for both runtime and editor tools.
	 */
	UFUNCTION(BlueprintCallable, Category = "Music Analysis")
	static UPcMusicAnalyzer* RunSongAnalysis(UObject* Outer, UPcMusicConfigurationData* SongConfig);

	// --- Public Data Accessors ---
	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	const TArray<FPcMusicGameplayEvents>& GetRhythmSections() const { return Result.RhythmSections; }

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	const TArray<FPcImportedMusicData>& GetRuntimeEventTimeline() const { return RuntimeEventTimeline; }

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	const TMap<int32, FPcImportedMusicData>& GetMasterUninheritedTimingPoints() const { return MasterUninheritedTimingPoints; }

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Analyzed Song Data")
	int32 GetAbsoluteSongEndTimeMS() const { return AbsoluteSongEndTimeMS; }

private:
	// --- Private Implementation ---

	// The main analysis logic. Called by RunSongAnalysis.
	void AnalyzeRhythmSections(const FPcSongAnalysisParameters& Parameters);

	// Gathers data about the different difficulties associated with this song
	bool GatherCouncilData(const TArray<UDataTable*>& WeightedAnalysisMaps, float DifficultyBias, TArray<FPcConfidentHitObject>& OutConfidentHitObjects);

	// --- Stored Analysis Results ---
	
	UPROPERTY()
	FPcSongAnalysisResult Result;

	UPROPERTY()
	TArray<FPcImportedMusicData> RuntimeEventTimeline;

	UPROPERTY()
	TMap<int32, FPcImportedMusicData> MasterUninheritedTimingPoints;

	UPROPERTY()
	int32 AbsoluteSongEndTimeMS = -1;
};