// --- START OF FILE SongConfigurationData.h ---

// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "PcMusicConfigurationData.generated.h"

class UMetaSoundSource;
class UDataTable;

/**
 * Data asset that holds all the configuration and generated assets for a single song.
 * The order of properties in the Details Panel is controlled by the UCLASS meta specifier below.
 */
UCLASS(BlueprintType, meta = (
	// "Asset Generation" category is removed as the button is now inside "Generated Assets"
	CategoryDisplayPriority = "General Music Data | 1, Core Gameplay Data | 2, Generated Assets | 3, Advanced | 4"
))
class PROJECT_CIRCLE_API UPcMusicConfigurationData : public UDataAsset
{
	GENERATED_BODY()

public:

	// --- General Music Data ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "General Music Data", meta = (DisplayPriority = "1"))
	FName SongName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "General Music Data", meta = (DisplayPriority = "2"))
	TObjectPtr<UMetaSoundSource> MainMusicMetaSound;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "General Music Data", meta = (DisplayPriority = "3"))
	TObjectPtr<USoundWave> SongWaveAsset;

	// --- CORE GAMEPLAY DATA ---
	/** The specific DataTable whose notes will be used for gameplay events. This is the notes that are played. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Core Gameplay Data", meta = (RowType = "PcMusicGameplayNotes", DisplayPriority = "4"))
	TObjectPtr<UDataTable> MusicGameplayNotesProfile;

	/** This Data Table is used to map the events that will be in the main song. (Eg. Beat drops, beat pace changed etc..) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Core Gameplay Data", meta = (RowType = "PcMusicGameplayEvents", DisplayPriority = "5"))
	TObjectPtr<UDataTable> MusicEventsProfile;

	// --- GENERATED GAMEPLAY ASSETS ---
	/** The final, processed events data used for gameplay. This is generated by the 'GenerateRhythmAssets' function. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets", meta = (DisplayPriority = "6"))
	TObjectPtr<UDataTable> GeneratedMusicEventsProfile;

	/** A copy of the GameplayMap, used for runtime note events. This is generated by the 'GenerateRhythmAssets' function. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets", meta = (DisplayPriority = "7"))
	TObjectPtr<UDataTable> GeneratedMusicNotesProfile;

#if WITH_EDITOR
	/**
	 * Runs the full song analysis and generates the Music Events Profile and Gameplay Notes DataTables.
	 * The generated assets will be automatically assigned to the 'Generated Assets' properties above.
	 */
	// CHANGE: The button is now in the "Generated Assets" category to group it with its output.
	// CHANGE: Its DisplayPriority is higher than the properties above it, so it appears last in the group.
	UFUNCTION(CallInEditor, Category = "Generated Assets", meta = (DisplayPriority = "8"))
	void GenerateRhythmAssets();
#endif

	// --- RHYTHM ANALYSIS DATA ---
	/** All other DataTables to be used for rhythm analysis. The GameplayMap should NOT be included in this list. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Advanced", meta = (AdvancedDisplay, DisplayPriority = "9"))
	TArray<TObjectPtr<UDataTable>> AdditionalAnalysisMaps;

	/** We do the same for this one. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Advanced", meta = (AdvancedDisplay, ClampMin = "-1.0", ClampMax = "1.0", DisplayPriority = "10"))
	float DifficultyBias = 0.0f;
};