#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "PcMusicConfigurationData.generated.h"

class UDataTable;

UCLASS(BlueprintType)
class PROJECT_CIRCLE_API UPcMusicConfigurationData : public UDataAsset
{
	GENERATED_BODY()

public:
	// --- CORE GAMEPLAY DATA ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gameplay")
	TObjectPtr<UDataTable> GameplayMap;

	// --- GAMEPLAY BPM ---
	/**
	 * The default gameplay BPM for this song.
	 *
	 * Any rhythm section whose GameplayBPM column is left at 0 in the
	 * generated DataTable will use this value instead.
	 *
	 * In most cases you only need to set this one number and never touch
	 * the DataTable at all. The subdivision is calculated automatically:
	 *   subdivision = round(rawBPM / DefaultGameplayBPM)
	 *
	 * Example: song has sections at 110, 220, 440 BPM.
	 *   DefaultGameplayBPM = 110
	 *   → 110 section: subdivision 1 (jump every beat)
	 *   → 220 section: subdivision 2 (jump every 2nd beat)
	 *   → 440 section: subdivision 4 (jump every 4th beat)
	 *   All sections feel the same tempo to the player.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gameplay|BPM",
		meta = (ClampMin = "1.0", ClampMax = "300.0"))
	float DefaultGameplayBPM = 110.f;

	// --- RHYTHM ANALYSIS DATA ---
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Analysis")
	TArray<TObjectPtr<UDataTable>> AdditionalAnalysisMaps;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Analysis", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
	float DifficultyBias = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Analysis", meta=(DisplayName="Structural Base Map (Optional Override)"))
	TObjectPtr<UDataTable> StructuralAnalysisBaseMapOverride;

	// --- GENERATED GAMEPLAY ASSETS ---
	/**
	 * Generated by GenerateRhythmAssets.
	 * Optionally fill the GameplayBPM column per-row to override DefaultGameplayBPM
	 * for specific sections of the song.
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets")
	TObjectPtr<UDataTable> GeneratedRhythmProfile;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Generated Assets")
	TObjectPtr<UDataTable> GeneratedNoteData;

#if WITH_EDITOR
	UFUNCTION(CallInEditor, Category = "Generated Assets")
	void GenerateRhythmAssets();
#endif
};